### ISSUE TITLE
Stimela considers out of date MeasTables as errors

### ISSUE THREAD

**Issue by landmanbester** [caracal-pipeline/stimela2#121]
I am not sure if this is the intended behaviour but stimela falls over when the eg. the leap second table is out of date. Here is the recipe output
```
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO: ### validated inputs
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO: cab gaincal:
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   vis = data/1559937657.PRIMARY.1.0.1.1.ghz.avg832khz32s.12ants.scan2.3.ms
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   caltable = prim.K0
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   field = J1939-6342
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   spw =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   intent =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   selectdata = True
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   timerange =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   uvrange =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   antenna =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   scan =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   observation =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   msselect =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   solint = inf
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   combine =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   preavg = -1.0
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   refant = m000
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   refantmode = flex
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   minblperant = 4
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   minsnr = 3.0
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   solnorm = False
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   gaintype = K
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   smodel = []
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   calmode = ap
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   solmode =
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   rmsthresh = []
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   append = False
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   docallib = False
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   gaintable = []
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   gainfield = []
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   interp = []
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   spwmap = []
2023-01-04 12:09:35 STIMELA.gotriA.primK INFO:   parang = False
### running casa --log2term --nologger --nologfile -c import sys, json; kw=json.loads(sys.argv[-1]); kw={key: (str(value) if type(value) is unicode else value) for key, value in kw.items()}; gaincal(**kw);
{"vis": "data/1559937657.PRIMARY.1.0.1.1.ghz.avg832khz32s.12ants.scan2.3.ms", "caltable": "prim.K0", "field": "J1939-6342", "spw": "", "intent": "", "selectdata": true, "timerange": "", "uvrange": "", "antenna":
"", "scan": "", "observation": "", "msselect": "", "solint": "inf", "combine": "", "preavg": -1.0, "refant": "m000", "refantmode": "flex", "minblperant": 4, "minsnr": 3.0, "solnorm": false, "gaintype": "K",
"smodel": [], "calmode": "ap", "solmode": "", "rmsthresh": [], "append": false, "docallib": false, "gaintable": [], "gainfield": [], "interp": [], "spwmap": [], "parang": false}
#
# =========================================
# The start-up time of CASA may vary
# depending on whether the shared libraries
# are cached or not.
# =========================================
#
# /opt/casalite/lib/python2.7/site-packages/IPython/core/interactiveshell.py:724: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
#   warn("Attempting to work in a virtualenv. If you encounter problems, please "
#
#
# CASA 5.6.0-60   -- Common Astronomy Software Applications
#
# Found an existing telemetry logfile: /home/landman/.casa/casastats-560-60-15013f1d9d01bb10e-20230104-093420.log
# Telemetry initialized. Telemetry will send anonymized usage statistics to NRAO.
# You can disable telemetry by adding the following line to your ~/.casarc file:
# EnableTelemetry: False
# 2023-01-04 10:09:37   INFO    ::casa  CASA Version  5.6.0-60
# --> CrashReporter initialized.
# 2023-01-04 10:09:38   INFO    gaincal::::
# 2023-01-04 10:09:38   INFO    gaincal::::+    ##########################################
# 2023-01-04 10:09:38   INFO    gaincal::::+    ##### Begin Task: gaincal            #####
# 2023-01-04 10:09:38   INFO    gaincal::::     gaincal(vis="data/1559937657.PRIMARY.1.0.1.1.ghz.avg832khz32s.12ants.scan2.3.ms",caltable="prim.K0",field="J1939-6342",spw="",intent="",
# 2023-01-04 10:09:38   INFO    gaincal::::+            selectdata=True,timerange="",uvrange="",antenna="",scan="",
# 2023-01-04 10:09:38   INFO    gaincal::::+            observation="",msselect="",solint="inf",combine="",preavg=-1.0,
# 2023-01-04 10:09:38   INFO    gaincal::::+            refant="m000",refantmode="flex",minblperant=4,minsnr=3.0,solnorm=False,
# 2023-01-04 10:09:38   INFO    gaincal::::+            normtype="mean",gaintype="K",smodel=[],calmode="ap",solmode="",
# 2023-01-04 10:09:38   INFO    gaincal::::+            rmsthresh=[],append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,
# 2023-01-04 10:09:38   INFO    gaincal::::+            docallib=False,callib="",gaintable=[],gainfield=[],interp=[],
# 2023-01-04 10:09:38   INFO    gaincal::::+            spwmap=[],parang=False)
# 2023-01-04 10:09:38   INFO    gaincal::calibrater::open       ****Using NEW VI2-driven calibrater tool****
# 2023-01-04 10:09:38   INFO    gaincal::calibrater::open       Opening MS: data/1559937657.PRIMARY.1.0.1.1.ghz.avg832khz32s.12ants.scan2.3.ms for calibration.
# 2023-01-04 10:09:38   INFO    gaincal::Calibrater::   Initializing nominal selection to the whole MS.
# 2023-01-04 10:09:38   INFO    gaincal::::     NB: gaincal automatically excludes auto-correlations.
# 2023-01-04 10:09:38   INFO    calibrater::setdata     Beginning selectvis--(MSSelection version)-------
# 2023-01-04 10:09:38   INFO    calibrater::reset       Reseting solve/apply state
# 2023-01-04 10:09:38   INFO    Calibrater::selectvis   Performing selection on MeasurementSet
# 2023-01-04 10:09:38   INFO    Calibrater::selectvis+   Selecting on field: 'J1939-6342'
# 2023-01-04 10:09:38   INFO    Calibrater::selectvis+   Selecting with TaQL: 'ANTENNA1!=ANTENNA2'
# 2023-01-04 10:09:38   INFO    Calibrater::selectvis   Selection did not drop any rows
# 2023-01-04 10:09:38   INFO    Calibrater::selectvis   Frequency selection: Selecting all channels in all spws.
# 2023-01-04 10:09:38   INFO    calibrater::setdata     chanmode=none nchan=1 start=0 step=1 mStart='0km/s' mStep='0km/s' msSelect='ANTENNA1!=ANTENNA2'
# 2023-01-04 10:09:38   INFO    calibrater::setsolve    Beginning setsolve--(MSSelection version)-------
# 2023-01-04 10:09:38   INFO    Calibrater::setsolve    Arranging to SOLVE:
# 2023-01-04 10:09:38   INFO    Calibrater::setsolve    .   K Jones: table=prim.K0 append=false solint=inf refantmode='flex' refant='m000' minsnr=3 apmode=AP solnorm=false
# 2023-01-04 10:09:38   INFO    calibrater::solve       Beginning solve-----------------------------
# 2023-01-04 10:09:38   INFO    Calibrater::solve       The following calibration terms are arranged for apply:
# 2023-01-04 10:09:38   INFO    Calibrater::solve       .   (None)
# 2023-01-04 10:09:38   INFO    Calibrater::solve       The following calibration term is arranged for solve:
# 2023-01-04 10:09:38   INFO    Calibrater::solve       .   K Jones: table=prim.K0 append=false solint=inf refantmode='flex' refant='m000' minsnr=3 apmode=AP solnorm=false
# 2023-01-04 10:09:38   INFO    Calibrater::solve       For solint = inf, found 2 solution intervals.
⚠  2023-01-04 10:09:39  SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)  Leap second table TAI_UTC seems out-of-date.
⚠  2023-01-04 10:09:39  SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)+ Until the table is updated (see the CASA documentation or your system admin),
⚠  2023-01-04 10:09:39  SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)+ times and coordinates derived from UTC could be wrong by 1s or more.
# 2023-01-04 10:09:41   INFO    Calibrater::solve         Found good K Jones solutions in 2 solution intervals.
# 2023-01-04 10:09:41   INFO            Writing solutions to table: prim.K0
# 2023-01-04 10:09:41   INFO    calibrater::solve       Finished solving.
# 2023-01-04 10:09:41   INFO    gaincal::::     Calibration solve statistics per spw:  (expected/attempted/succeeded):
# 2023-01-04 10:09:41   INFO    gaincal::::       Spw 0: 2/2/2
# 2023-01-04 10:09:41   INFO    gaincal::::     ##### End Task: gaincal              #####
# 2023-01-04 10:09:41   INFO    gaincal::::+    ##########################################
2023-01-04 12:09:43 STIMELA.gotriA.primK ERROR: declaring 'gaincal' as failed based on its output
2023-01-04 12:09:43 STIMELA.gotriA.primK INFO: gaincal returns exit code 0 after 0:00:07
2023-01-04 12:09:43 STIMELA.gotriA.primK ERROR: step 'gotriA.primK' has failed, aborting the recipe
────────────────────────────────────────────────────────────────────────────────────────── detailed error report follows ──────────────────────────────────────────────────────────────────────────────────────────
        ⚠ step 'gotriA.primK' has failed, aborting the recipe
        └── error running cab 'gaincal'
            ├── CASA error:     SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)  Leap second table TAI_UTC seems out-of-date.
            ├── CASA error:     SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)+ Until the table is updated (see the CASA documentation or your system admin),
            └── CASA error:     SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4290)+ times and coordinates derived from UTC could be wrong by 1s or more.
```
So CASA has succeeded, albeit with an out of date table, but stimela still falls over. Maybe this specific error should be ignored? Anyone seen this before and has a workaround?

**Comment by bennahugo** [comment]
It is not an error but, so it should not fall over. You can update it from NRAO directly
https://github.com/cyriltasse/DDFacet/blob/master/docker.2004#L114

**Comment by o-smirnov** [comment]
Yeah I'm gonna gonna have to add an exception to the output wrangler to work around that. At the moment if CASA says SEVERE anything, stimela assumes it has a good reason to do so and marks the cab in error. (Original problem being that in 2022, CASA still does not stoop to returning error codes!!! So the only way to tell if a cab has failed is to look for error messages in the console output :man_facepalming:.)

Also, you can put this into your ``~/.casarc``:
```
measures.directory: /usr/share/casacore/data
```

It will then use the ``casacore-data`` KERN package, which is reasonably up to date.

**Comment by landmanbester** [comment]
Yup, updating the casacore-data manually using eg.
```
rsync -avz rsync://casa-rsync.nrao.edu/casa-data /usr/share/casacore/data/
```
and adding the above to the rc file with eg
```
$ echo 'measures.directory: /usr/share/casacore/data' > .casarc
```
works. Thanks

**Comment by abhisek176** [comment]
Hi @o-smirnov, @landmanbester: Is there any latest update on Stimela, version 2.0? or How to fix this in the HPC environment? 

Thanks very much.

Update:
I am using this now. Hopefully, it will solve it. 
    management:
      wranglers:
        'Error in FLAG command:':
          - ERROR

**Comment by o-smirnov** [comment]
@abhisek176 which cab are you running? Or did you roll your own? 

The issue is that the wrangler catching SEVERE and ABORTING messages is hardcoded here:

https://github.com/caracal-pipeline/stimela/blob/1c6a973605d611ae6908028ca8c588fe6de2da4b/stimela/backends/flavours/casa.py#L30

The solution is to modify the regex to not match "SEVERE  MeasTable". Something like "SEVERE\s+(?!MeasTable)" ought to do the trick.

I'll fix this for 2.0.1, but in the meantime try the above workaround please. Note to self, consider moving this wrangler out to ``stimela.conf`` rather than hardcoding it, so that users can fiddle with it without touching the codebase.

**Comment by abhisek176** [comment]
I was looking for this file. Thanks very much @o-smirnov . I am trying a custom casa flagging cab.

**Comment by o-smirnov** [comment]
Excellent! Please consider contributing to ``cult-cargo`` if you think this cab will be useful to the community.

**Comment by abhisek176** [comment]
HI @o-smirnov, I am still facing interruptions. Could you please check what's wrong?

Below is the cab:

  rflag-flag:
    command: flagdata
    flavour: casa-task
    inputs:
      vis: 
        dtype: MS
        required: true
        default: '{recipe.ms}'
      mode:
        dtype: str
        default: rflag
        info: Flagging mode
        choices:
          - list
          - manual
          - clip
          - quack
          - tfcrop
          - rflag
      datacolumn:
        dtype: str
        default: 'RESIDUAL'
        info: Column to flag
      field:
        dtype: str
        default: ''
        info: Field names or ids (blank for all)
      timecutoff:
        dtype: float
        default: 5.0
        info: Time cutoff in standard deviations
      freqcutoff:
        dtype: float
        default: 5.0
        info: Frequency cutoff in standard deviations
      timefit:
        dtype: str
        default: 'line'
        info: Fit type for time
        choices:
          - line
          - poly
      freqfit:
        dtype: str
        default: 'line'
        info: Fit type for frequency
        choices:
          - line
          - poly
      flagdimension:
        dtype: str
        default: 'freqtime'
        info: Dimensions for flagging
      extendflags:
        dtype: bool
        default: false
        info: Extend flags to neighboring channels or time slots
      timedevscale:
        dtype: float
        default: 3.0
        info: Scaling factor for time deviations
      freqdevscale:
        dtype: float
        default: 3.0
        info: Scaling factor for frequency deviations
      spectralmax:
        dtype: int
        default: 500
        info: Maximum number of spectral channels to process
      extendpols:
        dtype: bool
        default: false
        info: Extend flags across polarizations
      growaround:
        dtype: bool
        default: false
        info: Grow flags around outliers
      flagneartime:
        dtype: bool
        default: false
        info: Flag nearest time slots
      flagnearfreq:
        dtype: bool
        default: false
        info: Flag nearest frequency channels
      action:
        dtype: str
        default: 'apply'
        info: Action to perform (apply or calculate)
        choices:
          - apply
          - calculate
      flagbackup:
        dtype: bool
        default: true
        info: Create a backup of flags before applying
      overwrite:
        dtype: bool
        default: true
        info: Overwrite existing flags
      writeflags:
        dtype: bool
        default: true
        info: Write flags to the FLAG column
    management:
      wranglers:
        'Error in FLAG command:':
          - ERROR
          

My inputs are:

    flag-after-peelsun-selfcal:
      cab: rflag-flag
      info: "Flagging after peeling SUN"
      params:
        vis: '{root.ms}'
        mode: rflag 
        
     
I changed the line to _err_patt = re.compile("(?P<content>(SEVERE\s+(?!MeasTable))(.*))$")_


Still getting the following error:


2024-08-28 19:01:52 STIMELA.solarkat.flag-after-peelsun-selfcal ERROR: declaring
'flagdata' as failed based on its output                                        
2024-08-28 19:01:52 STIMELA.solarkat.flag-after-peelsun-selfcal INFO: flagdata  
returns exit code 0 after 0:22:55                                               
2024-08-28 19:01:52 STIMELA.solarkat.flag-after-peelsun-selfcal ERROR: step     
'solarkat.flag-after-peelsun-selfcal' has failed, aborting the recipe           
──────────────────────── detailed error report follows ─────────────────────────
        ⚠ step 'solarkat.flag-after-peelsun-selfcal' has failed, aborting the   
        recipe                                                                  
        └── error running cab 'flagdata'                                        
            ├── CASA error: SEVERE      MeasTable::dUTC(Double) (file           
            │   ../../measures/Measures/MeasTable.cc, line 4290)  Leap second   
            │   table TAI_UTC seems out-of-date.                                
            ├── CASA error: SEVERE      MeasTable::dUTC(Double) (file           
            │   ../../measures/Measures/MeasTable.cc, line 4290)+ Until the     
            │   table is updated (see the CASA documentation or your system     
            │   admin),                                                         
            └── CASA error: SEVERE      MeasTable::dUTC(Double) (file           
                ../../measures/Measures/MeasTable.cc, line 4290)+ times and     
                coordinates derived from UTC could be wrong by 1s or more. 
                

Many thanks!

**Comment by o-smirnov** [comment]
It looks like the regex is not ignoring that line correctly, but I can't see the problem from just eyeballing. Try playing with the regex, and I'll have a closer look when I'm at the laptop tomorrow.

**Comment by abhisek176** [comment]
Sure, though I checked in Python and it picks the lines:

Matched content: SEVERE  MeasTable::dUTC(Double) (file                   
Matched content: SEVERE  MeasTable::dUTC(Double) (file                   
Matched content: SEVERE  MeasTable::dUTC(Double) (file 

but somehow not stitching back.

**Comment by abhisek176** [comment]
Hi @o-smirnov, it worked. Just needed to reload the environment. Thanks very much for looking into it.

**Comment by Athanaseus** [comment]
@abhisek176 there is a `casa-flag` cab available in `cult-cargo` master, feel free to give it a spin.
PR: https://github.com/caracal-pipeline/cult-cargo/pull/56

**Comment by abhisek176** [comment]
@Athanaseus Thanks very much!
