### ISSUE TITLE
Stimela without user

### ISSUE THREAD

**Issue by NicolaMalavasi** [caracal-pipeline/stimela2#156]
Hello, I would like to report an issue and ask for possible solutions.

I am trying to use caracal (and therefore stimela) on a new infrastructure. By design, on this cluster the user caracal gets run with is "nobody". Not sure this is the correct terminology, but when I try to launch a caracal task I get a stimela error. Cabs are pre-pulled to a local folder and accessed through singularity.

```Traceback (most recent call last):
  File "/usr/local/bin/caracal", line 4, in <module>
    import caracal.main as main
  File "/usr/local/lib/python3.8/site-packages/caracal/__init__.py", line 8, in <module>
    import stimela
  File "/usr/local/lib/python3.8/site-packages/stimela/__init__.py", line 17, in <module>
    USER = os.environ["USER"]
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'
```

I do seem to understand that stimela requests from the system some user information and this does not exist for user "nobody". How is this information used by stimela? Is it necessary or can the lines in the stamina `__init__.py` file be commented out without risk? Is there a way to circumvent this and run caracal/stimela as user "nobody"?

**Comment by o-smirnov** [comment]
Hi @NicolaMalavasi, sorry I missed this... wrong repo actually (but I realize we've created the confusion ourselves with our naming eh @SpheMakh?), this repo is for Stimela2, whereas caracal uses Stimela classic. So I copied this to https://github.com/ratt-ru/Stimela/issues/784

**Comment by o-smirnov** [comment]
@NicolaMalavasi can you please replace
```
    USER = os.environ["USER"]
```
with
```
    USER = os.getlogin()
```
and see if that works? I think the latter is the "correct" way to get the username.

**Comment by sphemakh** [comment]
Fixed in stimela-classic.
