### ISSUE TITLE
poetry install fails with "Failed to create the collection: Prompt dismissed.."

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#160]
Very annoying... workaround is to do:

```
export PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring
```

(see https://github.com/python-poetry/poetry/issues/5250)

But perhaps @SpheMakh has a more sustainable solution?

**Comment by sphemakh** [comment]
Seems to be fixed, except for private repos or dependencies. Are you still getting the error?

**Comment by o-smirnov** [comment]
Haven't seen it for a while, so let's assume i's been fixed in poetry (continuing complaints on linked issue notwithstanding).
