### ISSUE TITLE
validate_parameters for remote backends needs to know about non-existence of files

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#162]
The current use case is the ``kube`` backend. Parameter validation does not have access to the remote filesystem (necessarily), so should not check for the existence of files and directories.

I've worked around this by setting the ``loosely`` argument to validate, but this has a slightly different meaning -- it also turns off checks for bad substitutions. We need a different argument that tells validate() that files are non-local and should be skipped. Note that ``skip_if_exists`` and such is also disabled for now, for the same reason .

Top prize would be adding the ability to check for remote files. To do this, stimela would need to start up a "service" pod that mounts the volumes, and can do file checks. Maybe @sjperkins has ideas about how to do this generically.

**Comment by sjperkins** [comment]
Just getting into this myself, but it looks like there are a variety of Kubernetes patterns out there which would be good to use:

https://developers.redhat.com/blog/2020/05/11/top-10-must-know-kubernetes-design-patterns

Maybe something like an **Init pattern** that tries to mount the remote filesystem in a small pod and reports back to Stimela as to whether the this succeeded? More practically one could use [Alpine Linux Containers](https://hub.docker.com/_/alpine) to do this, which are only ~5MB in size.

As an aside, I think stimela2 will end up mostly implementing the [Operator Pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) as it already uses the python kubernetes library to interface with the Kubernetes Control Plane.

**Comment by o-smirnov** [comment]
Works now I think.
