### ISSUE TITLE
report CPU/memory/etc metrics from kube backend

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#163]
When running the ``kube`` backend, the built-in profiling and status line is useless, as it only measures local resources.

Need to think of a scheme for more generic reporting. Kubernetes has an API for this: https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/

One obvious difficulty seems to be that the actual metrics reported are different for different Kubernetes implementations., i.e. k8s and EKS will return totally different structures. Something generic/configurable may be needed. Tagging @sjperkins for future reference (not a FIASCO3 problem!)

**Comment by sjperkins** [comment]
> Need to think of a scheme for more generic reporting. Kubernetes has an API for this: https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/

So the metrics server is installed on our EKS cluster: https://kubernetes-sigs.github.io/metrics-server/.

This SO answer presents one way to query this:

- https://stackoverflow.com/a/58407092


> Something generic/configurable may be needed. Tagging @sjperkins for future reference

I suspect a more comprehensive (and maybe heavier) solution would be to install Prometheus:

- https://prometheus.io/
- https://github.com/prometheus-operator/kube-prometheus

**Comment by o-smirnov** [comment]
Here's a poor man's solution in the meantime: do ``get pods`` (or its API equivalent rather), and report the number of pods in each state in the stimela status line. This is already valuable feedback to the user -- at least you can see the autoscaler do its thing.

**Comment by sjperkins** [comment]
> So the metrics server is installed on our EKS cluster: https://kubernetes-sigs.github.io/metrics-server/.
> 
> This SO answer presents one way to query this:
> 
> * https://stackoverflow.com/a/58407092

I should've also mentioned it's possible to query pod CPU and memory usage via

```
$ kubectl top nodes
$ kubectl -n namespace top pods 
```

**Comment by o-smirnov** [comment]
> 
> I should've also mentioned it's possible to query pod CPU and memory usage via
> 
> ```
> $ kubectl top nodes
> $ kubectl -n namespace top pods 
> ```

Ah cool! If this is a generic k8s API, then rather we support that, before investing effort into any custom metrics solution.

ChatGPT with a detailed explanation as usual:

To call `kubectl top pods` programmatically using the Kubernetes Python client, you need to interact with the metrics API (provided you have the Metrics Server set up in your cluster). The Kubernetes Python client provides methods to call various Kubernetes APIs, including the metrics API.

Here's a basic example of how you can use the Kubernetes Python client to retrieve pod metrics:

1. First, you'll need to install the Kubernetes Python client:

```bash
pip install kubernetes
```

2. Use the client to retrieve metrics:

```python
from kubernetes import client, config

def get_pod_metrics(namespace='default'):
    # Load kube config
    config.load_kube_config()

    # Define the API endpoint
    custom_api = client.CustomObjectsApi()

    # Depending on your Metrics Server setup and version, the group, version, and plural might differ.
    # The following is a common configuration:
    group = 'metrics.k8s.io'
    version = 'v1beta1'
    plural = 'pods'

    try:
        # Get metrics for all pods in the specified namespace
        metrics = custom_api.list_namespaced_custom_object(group, version, namespace, plural)
        
        for item in metrics['items']:
            pod_name = item['metadata']['name']
            for container in item['containers']:
                container_name = container['name']
                usage = container['usage']
                cpu_usage = usage.get('cpu', 'N/A')
                memory_usage = usage.get('memory', 'N/A')
                print(f"Pod: {pod_name}, Container: {container_name}, CPU: {cpu_usage}, Memory: {memory_usage}")

    except Exception as e:
        print(f"Error fetching metrics: {e}")

get_pod_metrics()
```

Note that the actual metrics you retrieve depend on the Metrics Server setup in your Kubernetes cluster. The example assumes a common setup, but there might be differences based on your particular configuration. You should adjust the API calls accordingly if your metrics setup is different.

Additionally, remember to set up proper Role-Based Access Control (RBAC) permissions for the account you're using to fetch metrics, ensuring it has the necessary permissions to access the metrics API.

**Comment by o-smirnov** [comment]
Implemented in https://github.com/caracal-pipeline/stimela/commit/29f90e536a4af2b1224fbcdf65ae5bdf8f68ba1c. Basic CPU and memory metrics collected and profiled.
