### ISSUE TITLE
Add SORT function to stimela

### ISSUE THREAD

**Issue by Victoria-Samboco** [caracal-pipeline/stimela2#166]
I would like to request the addition of a new function called SORT in Stimela. The SORT function would allow users to sort the input data based on a specific column or parameter (index number, time...), which is crucial for organizing and analyzing the data more effectively.
I find it very useful when we want to list files with GLOB and ensure they are being processed in the correct/desired order.

**Comment by o-smirnov** [comment]
Good idea... but I don't understand what you mean by "based on a specific column or parameter (index number, time...)". -- can you elaborate that thought a little please?

If I define a ``=SORT()`` function, it will expect a list of something, and we can do an alphanumeric sort on that list. There is no concept of "column" or "parameter" at that stage, it's just a list of objects.

I suppose we *can* define a specialized sort for lists of files or directories, to sort by e.g. filesystem timestamp.

**Comment by Victoria-Samboco** [comment]
> Good idea... but I don't understand what you mean by "based on a specific column or parameter (index number, time...)". -- can you elaborate that thought a little, please?
> 
In this case, I need a ='SORT()'  function to sort a list of objects alphanumerically to ensure that they are being processed in order and make it easy to control the process in my pipeline.

My bad, my intention was to say based on the index number and timestamp not exactly associated with columns.

**Comment by o-smirnov** [comment]
Done, on the ``FIASCO3`` branch for now. You've got SORT() and RSORT() for reverse order.

**Comment by Victoria-Samboco** [comment]
> Done, on the `FIASCO3` branch for now. You've got SORT() and RSORT() for reverse order.

Thank you
