### ISSUE TITLE
Stimela not recognising singularity images

### ISSUE THREAD

**Issue by Allycan** [caracal-pipeline/stimela2#168]
I have defined a `shadems` cab as follows;

```
visplots:
        info: 'plots visibilities of the simualted measurement set'
        backend:
          singularity:
            image_dir: '/idia/software/containers/caracal/STIMELA_IMAGES_1.7.7/'
        image: stimela_shadems_1.7.0.sif
        command: shadems
```

When I create a recipe with this cab, stimela runs `shadems` that is installed in my virtual environment but I wanted to execute my recipe using singularity. Does Stimela II have singularity support as yet? I see that this is still a work in progress as stated at [here](https://stimela.readthedocs.io/en/latest/reference/containers.html). Is there no way to work at least with containerised softwares such as `shadems`, `MeqTrees`, e.t.c?

At first I thought the cab was using the container as I did not get any issues/errors raised until I had to run the `MeqTrees` and `wsclean` cabs which are not installed in my environment nor the computing cluster.

```
step 'interferometricrecipe.wsclean' has failed, aborting the recipe                                                                     
            └── wsclean: not found
```

**Comment by Allycan** [comment]
...at first I had the `command` key defined as,
  `command: singularity run '/idia/software/containers/caracal/STIMELA_IMAGES_1.7.7/stimela_shadems_1.7.0.sif shadems`,

but this resulted in `# FATAL:   singularity image is not owned by required user(s)`, which I suppose is due to permission issues as I am working from Ilifu cluster.

**Comment by Allycan** [comment]
The problem with this is that I was running from a wrong compute node. I found that changing the node and maintaining the `command: singularity run '/idia/software/containers/caracal/STIMELA_IMAGES_1.7.7/stimela_shadems_1.7.0.sif shadems` works while the former format of defining a backend doesn't seem to work.

**Comment by o-smirnov** [comment]
Using ``command: singularity run`` was a clever workaround you've found -- that'll fool the native backend into running singularity.

The singularity backend proper is getting there... it's actually mostly functional, we just don't have all of the images in place yet. You might want to use the ``FIASCO3`` branch for now if you want to try the backend.

The way to properly enable the singularity backend is 

```yml
backend:
  select: singularity
  singularity:
     # whatever singularity options
```

...which can be done globally (under ``opts``), or per-cab, or even per-step. Singularity backend options are defined here: https://github.com/caracal-pipeline/stimela/blob/master/stimela/backends/singularity.py#L19. You probably want to disable auto_build, if you're using pre-built images.

Then there's image naming... ``image: stimela_shadems_1.7.0.sif`` won't work (but it would be a good feature to add, let me open an issue for that). The way it works currently, your cab must specify

```yml
image:
  registry: # optional, quay.io/stimela2 is default
  name: shadems
  version: 1.7.0
```

...and it forms up a filename for singularity images automatically based off that (and ``backend: singularity: image_dir``). So if you want to use your own pre-built image, the easiest way for now is to put a symlink at the location it expects.
