### ISSUE TITLE
Add support for pre-built singularity images

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#169]
As suggested here: https://github.com/caracal-pipeline/stimela/issues/168

As an alternative to the current automatic pull-and-build behaviour, allow the user to specify a path to a *.sif image directly.

**Comment by o-smirnov** [comment]
All right @Allycan, this is implemented on the ``issue-169`` branch which I'll also merge into ``FIASCO3`` shortly.

Specified as follows: 

```yml
cabs:
  cabname:
    image: 
      path: /path/to/image.sif
```

If no path is specified (in which case ``name`` must be), it reverts to the standard behaviour of pulling from our registry etc.

**Comment by Allycan** [comment]
@o-smirnov awesome, this is great.

**Comment by viralp** [comment]
Can we pull singularity images with stimela 2? In my installation, it did not automatic pull. Probably I am missing something? I do have old singularity images which I can import as Oleg suggested above, but I don't have all images, for instance Quartical.

**Comment by o-smirnov** [comment]
I think this works now.
