### ISSUE TITLE
detect failure modes in Kubernetes backend and bomb out

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#176]
Certain common failure conditions cause the workflow to hang. The default k8s behaviour seems to be to back off and wait for Godot, leaving the pod in Pending state forever. It would be good to detect such non-recoverable errors and bomb out gracefully with an error message instead.

The failure conditions are reported as k8s events, which the backend already collects. So it's just a matter of adding some heuristics about what kind of events represent a non-recoverable error. Opening this issue to collect such examples and heuristics (tagging @sjperkins).

* [ ] Example 1, pod refers to an unknown volume (PVC). Resulting events:

```
2023-09-06 12:19:57 STIMELA.recipe.mask1 INFO: [kubernetes event type: Warning, reason: FailedScheduling] 0/3 nodes are available: persistentvolumeclaim "rarg-test-compute-pvc" not      
found. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..                                                                                              
2023-09-06 12:20:02 STIMELA.recipe.mask1 INFO: [kubernetes event type: Normal, reason: NotTriggerScaleUp] pod didn't trigger scale-up: 19 persistentvolumeclaim "rarg-test-compute-pvc"   
not found, 1 max node group size reached                                                                                                                                                  
2023-09-06 12:21:30 STIMELA.recipe.mask1 INFO: [kubernetes event type: Warning, reason: FailedScheduling] 0/4 nodes are available: persistentvolumeclaim "rarg-test-compute-pvc" not      
found. preemption: 0/4 nodes are available: 4 No preemption victims found for incoming pod..                                                                                              
2023-09-06 12:25:06 STIMELA.recipe.mask1 INFO: [kubernetes event type: Normal, reason: NotTriggerScaleUp] pod didn't trigger scale-up: 1 max node group size reached, 19                  
persistentvolumeclaim "rarg-test-compute-pvc" not found                 
```                          

* [ ] Example 2, pod can't be provisioned due to resources (not enough nodes or whatever). 

Hypothesis 1: any event with ``type: Warning, reason: FailedScheduling`` is an excuse to bomb out?

* [x] Example 3, can't pull image. This is usually due to a malformed image name. Not sure how to detect this one yet.
 
* [x] perhaps add a hard (configurable) timeout for pod startup? E.g. if a pod is still Pending after 5 minutes, probably safe to assume that's not going to change.

**Comment by sjperkins** [comment]
Given the following command on a currently Pending pod

```bash
$ kubectl -n rarg-test-compute describe pods describe pods oms--recipe--mask1--c4243ba0
...
Events:
  Type     Reason             Age                      From                Message
  ----     ------             ----                     ----                -------
  Normal   NotTriggerScaleUp  6m45s (x138 over 3h27m)  cluster-autoscaler  pod didn't trigger scale-up: 1 max node group size reached, 19 persistentvolumeclaim "rarg-test-compute-pvc" not found
  Warning  FailedScheduling   3m25s (x44 over 3h29m)   default-scheduler   0/3 nodes are available: persistentvolumeclaim "rarg-test-compute-pvc" not found. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
  Normal   NotTriggerScaleUp  100s (x1088 over 3h29m)  cluster-autoscaler  pod didn't trigger scale-up: 19 persistentvolumeclaim "rarg-test-compute-pvc" not found, 1 max node group size reached
```

The `NotTriggerScaleUp` reason is given by the `cluster-autoscaler` (here, because it can't find the now renamed `rarg-test-compute-pvc`  persistentvolumeclaim) and so there's no point in trying to requisition an EC2 instance.

Then `FailedScheduling` is produced by the `default-scheduler` (i.e. kubernetes), also because `rarg-test-compute-pvc` isn't available and there are no pods that can be pre-empted from existing pods.

Quoting from https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-events-are-emitted-by-ca:

> Whenever Cluster Autoscaler adds or removes nodes it will create events describing this action. It will also create events for some serious errors. Below is the non-exhaustive list of events emitted by CA (new events may be added in future):
>
> on pods:
>
> - TriggeredScaleUp - CA decided to scale up cluster to make place for this pod.
> - NotTriggerScaleUp - CA couldn't find node group that can be scaled up to make this pod schedulable.
> - ScaleDown - CA will try to evict this pod as part of draining the node.

So a constant stream of `NotTriggerScaleUp` events are problematic because the autoscaler can't requisition appropriate instances. In turn they can probably cause a series of `FailedScheduling` events by the `default-scheduler`. `NotTriggerScaleUp`  shouldn't be considered the sole cause of `FailedScheduling` IMO.

**Comment by sjperkins** [comment]
> Certain common failure conditions cause the workflow to hang. The default k8s behaviour seems to be to back off and wait for Godot, leaving the pod in Pending state forever. It would be good to detect such non-recoverable errors and bomb out 
gracefully with an error message instead.

From https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-happens-in-scale-up-when-i-have-no-more-quota-in-the-cloud-provider

> From version 0.6.2, Cluster Autoscaler backs off from scaling up a node group after failure. Depending on how long scale-ups have been failing, it may wait up to 30 minutes before next attempt.

**Comment by o-smirnov** [comment]
* [ ] catch PVC provisioning errors. At least some of them generate an event with reason = ProvisioningFailed on the PVC.

**Comment by o-smirnov** [comment]
> * [ ]  catch PVC provisioning errors. At least some of them generate an event with reason = ProvisioningFailed on the PVC.

Actually this is simple to do in the existing event handler, just ask it to pick up events from more than one object.

**Comment by o-smirnov** [comment]
> Hypothesis 1: any event with `type: Warning, reason: FailedScheduling` is an excuse to bomb out?

This is false. Some FailedScheduling conditions are transitory. 

For the other examples above I have implemented error handling -- commit incoming.

**Comment by o-smirnov** [comment]
* [ ] another interesting failure mode:
```
2023-09-18 18:55:10 STIMELA.ratt-parrot.flag-save INFO: [k8s event type: Warning, reason: FailedAttachVolume] AttachVolume.Attach failed for volume "pvc-a92420f8-e220-49da-9883-7be3b972f4db" : rpc error: code 
= Internal desc = Could not attach volume "vol-0b1019e4e2fc2ef5c" to node "i-0c05a70b87c9761f8": attachment of disk "vol-0b1019e4e2fc2ef5c" failed, expected device to be attached but was attaching             
2023-09-18 18:56:57 STIMELA.ratt-parrot.flag-save INFO: [k8s event type: Warning, reason: FailedMount] Unable to attach or mount volumes: unmounted volumes=, unattached volumes=, failed to process volumes=[]: 
timed out waiting for the condition          
```

**Comment by o-smirnov** [comment]
This, on the other hand, is not a terminal failure condition: https://github.com/ratt-ru/kubernauts/issues/107

**Comment by o-smirnov** [comment]
So here's an annoying example of a ProvisioningFailed event that's non-recoverable and is definitely a user error.
```
2023-09-25 11:26:20 STIMELA.recipe.mask1 INFO: [k8s event type: Warning, reason: ProvisioningFailed] storageclass.storage.k8s.io "rarg-test-compute-ebs-sc-immediate" not found                                  
```
