### ISSUE TITLE
Support multiple config files via CLI

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/stimela2#191]
It would be useful to be able to specify multiple config files via the CLI. The logic would be that, given `cli file1 file2 file3`, their config would be merged such that the last specified file has the highest priority. This should be relatively simple as merging config is a very standard operation in OmegaConf. 

The motivation for this is that it would make partial config changes less cumbersome i.e. in my use case, I want to tamper with the backend options, but don't want to create dozens of almost identical config files. With this change, the small handful of backend options I want to tamper with could be placed in a separate file and then simply added via the cli.

**Comment by o-smirnov** [comment]
An excellent idea. Works on ``issue-191`` now, will issue a PR shortly.
