### ISSUE TITLE
EKS volume node affinity conflicts

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#193]
As reported by @JSKenyon and myself (@sjperkins we've discussed this a little too). Sometimes when a workflow creates a PVC (such as the wsclean temp volume) and tries to launch a pod, the pod just hangs there and fails to trigger scale-up with "X nodes have volume affinity conflicts", indefinitely.

I see a related discussion here: https://stackoverflow.com/questions/75507501/eks-nodes-had-volume-node-affinity-conflict, and strongly suspect it's AZ-related. I suspect instances created in other AZs can't talk to volumes across AZs.

From the StorageClasses in https://github.com/ratt-ru/kubernauts/blob/a961f1dd36522aee3854650650051b64d807eb7c/terraform/compute/ebs.tf#L310, I can see that PhysicalVolumes are currently constrained to af-south-1c.

Questions for @sjperkins: how does EKS decide which AZ a node can be brought up in? Is it even smart enough to go "hmmm, this pod has PVCs bound to volumes in zone 1c, I must therefore schedule this pod on a node in zone 1c"? 

If that intelligence is not there in the EKS controller, then it must be up to Stimela (and the recipe config) to ensure things are placed in the same AZ. So the second question is, does the pod spec have fields for specifying the AZ to bring it up in?

A third option, rather brute force, is to "bake" the AZ into the node classes. If it's baked as 1c into the storage classes, then the same one should be baked into the instance definitions.

**Comment by sjperkins** [comment]
I think this issue is more appropriate to the kubernauts repo? I'm going to close this and recreate it there.

Feel free to reopen if I'm making a mistake.
