### ISSUE TITLE
stimela stalled on crosby?

### ISSUE THREAD

**Issue by ktrehaeven** [caracal-pipeline/stimela2#196]
Hi

I've been running quite a heavy crystalball step in a stimela2 recipe. I think cball is finished doing its thing but stimela hasnt moved onto the next step in the recipe. And it doesn't look like any tasks are being run on the machine so maybe something is stuck. @o-smirnov ever seen this behaviour?
![Screenshot from 2023-12-18 17-15-28](https://github.com/caracal-pipeline/stimela/assets/77777044/ede32ae8-67b5-4153-8fc3-66cff5c7cd92)

**Comment by o-smirnov** [comment]
Does the ps command show a crystalball process?

**Comment by ktrehaeven** [comment]
Output of ps -a

PID TTY          TIME CMD
1119044 pts/2    00:20:12 stimela
1119128 pts/2    6-16:10:17 crystalball
2074416 pts/3    00:00:00 ps
3353514 pts/1    00:00:04 stimela
3353515 pts/1    00:00:04 stimela
3353516 pts/1    00:00:04 stimela
3353517 pts/1    00:00:05 stimela
3353518 pts/1    00:00:04 stimela
3353520 pts/1    00:00:04 stimela
3353521 pts/1    00:00:05 stimela

does this mean cball is still running?

**Comment by o-smirnov** [comment]
Yes, it's refusing to exit for whatever reason. Is the MS not open in another process per chance? Say a backgrounded pipeline? That would make it sit there and wait for a file lock.

Not a stimela problem then. Maybe @sjperkins can assist with a diagnosis, but he's on leave now so not until January.

I suggest you halt the pipeline, use ps to make sure you're not running anything else, then restart the step.
