### ISSUE TITLE
_include should support explicit "include from CWD" construct

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#198]
As picked up by @landmanbester:

Let's say package ``foo`` contains ``X.yml`` and ``Y.yml``, and ``X.yml`` does ``_include: Y.yml``.

Now we have a ``./test.yml``recipe containing ``_include: (foo)X.yml``. X is included correctly, but the results of its nested include of Y will depend on whether ``.`` contains a local ``Y.yml`` of its own or not -- because as implemented currently, the ``_include`` statement looks in the CWD first, then in a standard set of include paths, and then only in the package directory. So it will preferentially pick up a "local" version of Y instead of the package version. This can lead to confusing results.

On the other hand, there is a legit use case for "import local Y.yml if it exists, else use the packaged Y.yml".

Python solves the same problem with package/module paths by supporting an ``import .Z`` or ``from . import Z`` construct, the ``.`` indicating "I really do mean to import from here and not anywhere else!" 

I suppose a Pythonic solution would be to support an explicit ``_include: (.)Y.yml`` construct with the same semantics. This would force it to import Y from the directory of the containing file (and throw an error if it's not found), while ``_include: Y.yml`` would retain the current behaviour of looking in the standard set of include paths, starting from the CWD.

@landmanbester opinions?

**Comment by o-smirnov** [comment]
Note to self: include search paths are given here: https://github.com/caracal-pipeline/stimela/blob/1d8c0d23b2b03ad27db181e347ff68ae2925bcd7/scabha/configuratt/resolvers.py#L260

A "(.)" construct could be checked for here:
https://github.com/caracal-pipeline/stimela/blob/1d8c0d23b2b03ad27db181e347ff68ae2925bcd7/scabha/configuratt/resolvers.py#L228

And of course we could generalize it to ``_include: (./subdir)Y.yml``. Basically, if ``module`` starts with a dot, treat it as a path relative to the path of the including file.

**Comment by landmanbester** [comment]
This sounds like a very handy feature. Do you think it is possible to throw a more useful error message for the case I just encountered though?  I.e. ```_include: Y.yml``` should bail out if ```Y.yml``` ends up being included circularly. Otherwise stimela hangs for a bit before bailing out with something along the lines of
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```
