### ISSUE TITLE
call Python callables in separate process

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#20]
As implemented, #5 currently calls the requested function directly from within the main Stimela process.

It would be more robust to fork (or launch a ProcessPool) and call it from a subprocess, with behaviour a-la xrun_poll (i.e. interception stdout/stderr, cancelling on Ctrl+C).

**Comment by o-smirnov** [comment]
Fixed in #74 with the ``python-ext`` flavour. Questions though, @SpheMakh @landmanbester:

* Should this rather be the default? 

* Should we have the "inline" (i.e. calling directly Stimela's interpreter) python flavour at all? I don't see any benefits to it anymore, it just happened to be the first thing I implemented... and other runners (kubernetes, docker, slurm) would have to fall back to external Python anyway...

**Comment by landmanbester** [comment]
I was wondering what the point of it is. I can't see any benefits to it either

**Comment by o-smirnov** [comment]
Done in #89. Everything is eternal now.

**Comment by o-smirnov** [comment]
I mean, external :rofl:
