### ISSUE TITLE
Add module to ease the *scabha* barrier to entry

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/stimela2#222]
I'm using scabha as a parser for simms 2.0 and added [this module](https://github.com/wits-cfa/simms/blob/2c8baf23f89504c7f280b16252df5064df5957b3/simms/parser_config/utils.py) to help load parameter specification files

A runner then uses it to get a command-line parser as follows:

````python
import simms
from simms.parser_config.utils import load, load_sources
from scabha.schema_utils import clickify_parameters
import click
from omegaconf import OmegaConf

command = "observe"
sources = load_sources(["skysim", "telescope"])
config = load(command, use_sources=sources)


@click.command(command)
@click.version_option(str(simms.__version__))
@clickify_parameters(config)
def runit(**kwargs):
    opts = OmegaConf.create(kwargs)
    print(opts)
    
runit()
````

I think my `utils.py` module (or some version of it) linked here could be added to *scabha* to make things easier for casual users who want to adopt it as an argument parser.

**Comment by o-smirnov** [comment]
Could consider migrating those utility functions into ``schema_utils`` directly -- that module is not used anywhere in Stimela per se, but is meant to support other packages.
