### ISSUE TITLE
Pre validation errors

### ISSUE THREAD

**Issue by SirFelixOtieno** [caracal-pipeline/stimela2#338]
running into prevalidation errors while trying to use 
 vis: '{recipe.ms}' where ms is defined elsewhere

**Comment by o-smirnov** [comment]
It's hard to diagnose anything from such a terse error report. Can you please post the full recipe (perhaps as a gist?) and your console output, and link it here?

**Comment by SirFelixOtieno** [comment]
```yml
_include:
  - casacabs.yaml
opts:
  backend:
    select:
      - singularity
      - native
  log:
    enable: true
    name: log-{info.pipeline}
    symlink: log
    ext: .txt
    dir: logs
    nest: 2
    level: INFO
gopipeline:
  name: pipeline
  info: listing observation
  
  inputs:
    ms: 
     dtype: MS
     info: measurement set
     required: true
     abbreviation: ms

  steps:
    listprim:
     cab: casa.listobs
          
     params:
      vis: '{recipe.ms}'
```

```    
─────────────────────────────── prevalidation ─────────────────────────────────
2024-09-25 12:57:13 STIMELA INFO: pre-validating the recipe                     
2024-09-25 12:57:13 STIMELA ERROR: pre-validation of recipe 'gopipeline' failed 
──────────────────────── detailed error report follows ─────────────────────────
        ⚠ pre-validation of recipe 'gopipeline' failed                          
        └── step 'listprim' failed prevalidation                                
            └── unknown parameter 'gopipeline.listprim.vis' 
```

**Comment by o-smirnov** [comment]
In the future, when you post code or output, please surround it by triple backquotes so that github renders it nicely (I have edited your post above... click on edit and see what I've added.) A leading triple-backquote followed by "yml" will also enable syntax highlighting.

It's not a problem with ``recipe.ms`` -- rather I think your ``listobs`` cab doesn't know about a ``vis`` parameter. Check the cab definition, I think we might be calling the parameter ``ms``.

**Comment by SirFelixOtieno** [comment]
> In the future, when you post code or output, please surround it by triple backquotes so that github renders it nicely (I have edited your post above... click on edit and see what I've added.) A leading triple-backquote followed by "yml" will also enable syntax highlighting.
> 
> It's not a problem with `recipe.ms` -- rather I think your `listobs` cab doesn't know about a `vis` parameter. Check the cab definition, I think we might be calling the parameter `ms`.

noted with thanks
